[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
healthcheckPath = "/__rebecca_go/healthz"
healthcheckTimeout = 10
